"""Initial migration with hash-based IDs

Revision ID: 1b4ceb0073ec
Revises: 
Create Date: 2025-09-06 14:06:19.246736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4ceb0073ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finalised_datapoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_datapoint_id', sa.String(), nullable=True),
    sa.Column('final_label_map', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finalised_datapoints_id'), 'finalised_datapoints', ['id'], unique=False)
    op.create_index(op.f('ix_finalised_datapoints_original_datapoint_id'), 'finalised_datapoints', ['original_datapoint_id'], unique=False)
    op.create_table('original_inputs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('label_map_json', sa.JSON(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_original_inputs_id'), 'original_inputs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_original_inputs_id'), table_name='original_inputs')
    op.drop_table('original_inputs')
    op.drop_index(op.f('ix_finalised_datapoints_original_datapoint_id'), table_name='finalised_datapoints')
    op.drop_index(op.f('ix_finalised_datapoints_id'), table_name='finalised_datapoints')
    op.drop_table('finalised_datapoints')
    # ### end Alembic commands ###
