"""Add short_id fields

Revision ID: 26aba315e019
Revises: 1b4ceb0073ec
Create Date: 2025-09-06 15:31:43.138622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26aba315e019'
down_revision: Union[str, None] = '1b4ceb0073ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finalised_datapoints', sa.Column('short_id', sa.String(), nullable=True))
    op.create_index('idx_finalised_datapoints_short_id', 'finalised_datapoints', ['short_id'], unique=False)
    op.create_index(op.f('ix_finalised_datapoints_short_id'), 'finalised_datapoints', ['short_id'], unique=True)
    op.add_column('original_inputs', sa.Column('short_id', sa.String(), nullable=True))
    op.create_index('idx_original_inputs_short_id', 'original_inputs', ['short_id'], unique=False)
    op.create_index(op.f('ix_original_inputs_short_id'), 'original_inputs', ['short_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_original_inputs_short_id'), table_name='original_inputs')
    op.drop_index('idx_original_inputs_short_id', table_name='original_inputs')
    op.drop_column('original_inputs', 'short_id')
    op.drop_index(op.f('ix_finalised_datapoints_short_id'), table_name='finalised_datapoints')
    op.drop_index('idx_finalised_datapoints_short_id', table_name='finalised_datapoints')
    op.drop_column('finalised_datapoints', 'short_id')
    # ### end Alembic commands ###
